[package]
name = "libsignal-protocol-sys"
version = "0.1.0"
authors = ["Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
openssl-sys = "0.9.40"

[build-dependencies]
bindgen = "0.45.0"
cmake = "0.1.35"